#!/bin/bash
#For external-service
. /utils.sh

#Initializing variables
app_id=${CliqrCloud_ClientId}
password=${CliqrCloud_ClientKey}
tenant_id=${CliqrCloud_TenantId}
resource_group=${Cloud_Setting_ResourceGroup}
Cloud_Setting_StorageAccount=${Cloud_Setting_StorageAccount}
store=( $Cloud_Setting_StorageAccount )
storage_name=${store[1]}
os_type=Windows
language=${runtime}
app_name=${app_name}
location=${region}
app_package1=${AppPackage}
app_tier_name=${cliqrAppTierName}
app_type=${app_type}

# Sourcing variables from service directory
arg1=$1

#Function for creating function in azure function app
create_function(){
    python main.py deploy
    echo "deploy completed"
}

#Check error file is there
function executionStatus() {
 FILE="FAILURE"
 if [ -f $FILE ];
 then
    status=`cat $FILE`
    print_error "Service execution failed"
    print_error "error ins script"
    exit 127
  else
    FILE="SUCCESS"
    status="Service execution successful"
    print_log "$status"
 fi
}

#Function for creating functionapp in azure
create_functionapp(){
    print_log "Create function called"
    check_grp=`az group exists -n $resource_group`
    if [ "$check_grp" = true ] ; then
        grp_exists=true
    else
        python main.py resource
        grp_exists=false
    fi
    check_stor=`az storage account check-name --name $storage_name`
    if [[ $check_stor == *"AlreadyExists"* ]]; then
        stor_exists=true
    else
        python main.py storage
        stor_exists=false
    fi
    check_fnapp=`az functionapp list --resource-group $resource_group`
    if [[ $check_fnapp == *"$app_name.azurewebsites.net"* ]]; then
        fnapp_exists=true
        print_log "Function with $resource_group already exists"
    else
        python main.py create
        fnapp_exists=false
    	#calling create_function for zip deploy
    	create_function
    fi
}

login(){
        pip install --upgrade pip
        apk add --update build-base
        apk add libffi-dev openssl-dev
	apk update && apk add --no-cache python3
	apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev && \
	apk add --no-cache --update python3 && \
	if [ "$app_type" = "Web App" ] ; then
            pip3 install azure-cli
            pip3 install cryptography==2.5
            python3 webapp_main.py login
            python3 webapp_main.py createweb
        else
            pip install azure-cli
            pip install cryptography==2.5
            python main.py login
            create_functionapp
            echo "Completed"
        fi
        }

stop(){
    print_log "Stop function called"
    print_log ${storeexists}
    pip install --upgrade pip
    apk add --update build-base
    apk add libffi-dev openssl-dev
    pip install azure-cli
    pip install cryptography==2.5
    print_log "stroewexists"
    print_log ${storeexists}
    if [[ $check_valid != *"ERROR"* ]]; then
        az login --service-principal --username $app_id --password $password --tenant $tenant_id
        if [ "$app_type" = "Web App" ] ; then
            echo "Webapp deletes"
            resource=$app_id"_rg_Linux_centralus"
	    echo $resource
            print_log "az webapp delete --name $app_name --resource-group $resource"
            az webapp delete --name $app_name --resource-group $resource
        else
            az functionapp delete --name $app_name --resource-group $resource_group 
        fi
        if [ "${storeexists}" = false ] ; then
            print_log "Condition Came"
            print_log "az storage account delete -n $storage_name -g $resource_group --yes"
            #az storage account delete -n $storage_name -g $resource_group --yes
        fi
    fi
    sleep 5
}

runscripts() {
    case $arg1 in
        stop)
            echo "[INSTALL] Installing Packages"
            stop
            executionStatus
            ;;
                start)
                    echo "[START] Creating Function app"
                    login
                    executionStatus
                    ;;
                *)
                    exit 127
                        ;;

        esac

}

runscripts

result="hostName: $app_tier_name
ipAddress:
environment:
   storeexists: $stor_exists"


print_ext_service_result "$result"

sleep 30
