CREATE DATABASE IF NOT EXISTS mysqldb;
GRANT ALL PRIVILEGES ON *.* TO 'c3admin'@'%' IDENTIFIED BY 'C3@dmin!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'c3admin'@'localhost' IDENTIFIED BY 'C3@dmin!' WITH GRANT OPTION;
FLUSH PRIVILEGES;

