#!/bin/bash
#For external-service
. /utils.sh

cmd=$1

# RUN EVERYTHING AS ROOT
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
fi
pip install --upgrade pip
print_log "env() : `env`"
function executionStatus() {
 FILE="FAILURE"
 if [ -f $FILE ];
 then
    status=`cat $FILE`
    print_error "Service execution failed"
    print_error "error ins script"
    exit 127
  else
    FILE="SUCCESS"
    status="Service execution successful"
    print_log "$status"
 fi
}

case $cmd in
	start)
		print_log "Executing Service.."
		python install_setup.py
		sleep 10
		python googlefunction.py start
		sleep 100
		executionStatus
		;;
		
	stop)
		print_log "Deleting Service.."
		python install_setup.py
		sleep 10
		python googlefunction.py stop
		executionStatus
		;;
	*)
		serviceStatus="Invalid command"
		exit 127
		;;
esac

