#!/bin/bash

exec > >(tee -a /usr/local/osmosix/logs/service.log) 2>&1

# Service Home Directory
OSSVC_HOME=/usr/local/osmosix/service

. /usr/local/osmosix/etc/.osmosix.sh
. /usr/local/osmosix/etc/userenv
. $OSSVC_HOME/utils/cfgutil.sh
. $OSSVC_HOME/utils/nosqlutil.sh
. $OSSVC_HOME/utils/install_util.sh

# Input
cmd=$1
SVCNAME=splunk

export HOME=/root

# Install WGET
installWget
if [ $? -ne 0 ]
then
    log "[ERROR] Failed to install wget"
    exit 1
fi

# Install Splunk Server
installSplunkServer() {
    wget -O splunk-6.5.3-36937ad027d4-Linux-x86_64.tgz 'http://download.splunk.com/products/splunk/releases/6.5.3/splunk/linux/splunk-6.5.3-36937ad027d4-Linux-x86_64.tgz'
    #wget -O splunk-6.5.3-36937ad027d4-linux-2.6-x86_64.rpm 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=6.5.3&product=splunk&filename=splunk-6.5.3-36937ad027d4-linux-2.6-x86_64.rpm&wget=true'
    chmod 744 splunk-6.5.3-36937ad027d4-Linux-x86_64.tgz
    tar xvzf splunk-6.5.3-36937ad027d4-Linux-x86_64.tgz -C /opt

    echo 'export SPLUNK_HOME="/opt/splunk"' >> $HOME/.bashrc
    echo 'export SPLUNK_HOME="/opt/splunk"' >> /usr/local/osmosix/etc/userenv

    /opt/splunk/bin/splunk start --accept-license
    /opt/splunk/bin/splunk enable boot-start
}

# Configure Splunk Server
configureServer() {
    stop

    /opt/splunk/bin/splunk set web-port $serverPort -auth admin:changeme
    /opt/splunk/bin/splunk enable listen $receiverPort -auth admin:changeme
}

# Start Splunk Server
start() {
  /opt/splunk/bin/splunk start
 
   return 0
} 
 
# Stop Splunk Server
stop() {
  /opt/splunk/bin/splunk stop
 
  return 0
} 

# Logger for Service
log() {
	logger -t "OSMOSIX" "[$SVCNAME] $*"
}

# main entry
if [ -z "$OSSVC_HOME" ]; then
	log "missing parameter, exit now"
	exit 127
fi

# Service Home directory
SVCHOME="$OSSVC_HOME/$SVCNAME"

# Agent Life Cyle Actions
runScripts(){
    case $cmd in
        install)
            log "[INSTALL] Installing $SVCNAME"
            installSplunkServer
            ;;
        deploy)
            echo "[DEPLOY] Deploy"
            ;;
        configure)
            echo "[CONFIGURE] configuring Splunk Server"
            configureServer
            ;;
        start)
            echo "[CONFIGURE] Starting Splunk Server"
            start
            ;;
        stop)
            echo "[STOP] stop Splunk Server"
            stop
            ;;
        restart)
            stop
            start
            echo "[RESTART] Invoking pre-restart user script"
            echo "[RESTART] Restarting $SVCNAME"
            echo "[RESTART] Invoking post-restart user script"
            ;;
        cleanup)
            echo "cleanup"
            ;;
        reload)
            echo "reload"
            ;;
        upgrade)
            echo "upgrade"
            ;;
        *)
            exit 127
            ;;
    esac
}

runScripts

