#!/bin/bash
# Author: Riyas Ahamed
# Type: External Service Azure Load Balancer

#For external-service
#. /utils.sh

cmd=$1

# RUN EVERYTHING AS ROOT
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
fi



# Return execution status
function executionStatus() {
 FILE="FAILURE"
 if [ -f $FILE ];
 then
    status=`cat $FILE`
    print "Configuration Failed"
    #print_log "$status"
    exit 127   
  else
    FILE="SUCCESS"
    status="Successfully Configured"
    #print_log "$status"
 fi
}

# External Life-Cycle actions
# - ACTIONS
#      - START
#          - Install Required Python Packages
#          - Create Load Balancer with configuration
#          - Attached with dependent tier application
#      - STOP
#          - Install Required Python Packages
#          - Delete Load Balancer
#          - Detached with dependent tier
case $cmd in
	start)
		#print_log "Executing Service.."
        python install_setup.py start
		executionStatus
		exit 0
		;;
	stop)
		echo "Service Action -  $cmd"
		python install_setup.py stop
		executionStatus
        exit 0
		;;
	*)
		echo "unknown command"
		exit 127
		;;
esac
