#!/bin/bash
#For external-service
. /utils.sh

cmd=$1

# RUN EVERYTHING AS ROOT
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
fi

pip install --upgrade pip

pip list
print_log "env() : `env`"
# while executing shell error msg will write on FAILURE file.
function executionStatus() {
 FILE="FAILURE"
 if [ -f $FILE ];
 then
    status=`cat $FILE`
    print_error "Service execution failed"
    print_error "$status"
    exit 127
  else
    FILE="SUCCESS"
    status="Service execution successful"
    print_log "$status"
 fi
}

# Start command will install required python peackages
# Will invoke the google sdk and creating load balancer
# stop command delete load balancer and uninstall python packages.
case $cmd in
	start)
		print_log "Executing Service.."
		python install_setup.py
		sleep 10
		python google_management.py start
		sleep 3m
		executionStatus
		;;
	stop)
		print_log "Deleting Service.."
		python install_setup.py
		sleep 10
		python google_management.py stop
		sleep 3m
		executionStatus
		;;
	*)
		serviceStatus="Invalid command"
		exit 127
		;;
esac

